<?php


namespace App\Tests\Services\Maps;
use App\Data\MapsDTO;
use App\Services\Maps\OpenStreetMaps;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;


class OpenStreetMapsTest extends WebTestCase
{
    private $logger;
    private $client;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::bootKernel();
        $container = self::$container;
        $this->logger = $container->get('monolog.logger');
        $this->client = $container->get('http_client');
    }

    /**
     * @dataProvider mapsDataProvider
     */
    public function testGetCoordinates($address, $latitude, $longitude) {
        $googleMaps = new OpenStreetMaps($this->client, $this->logger);
        $mapsDto = $googleMaps->search($address);

        self::assertInstanceOf(MapsDTO::class, $mapsDto);
        self::assertObjectHasAttribute('address', $mapsDto);
        self::assertObjectHasAttribute('longitude', $mapsDto);
        self::assertObjectHasAttribute('latitude', $mapsDto);
        self::assertEquals($mapsDto->address, $address);
        self::assertEquals($mapsDto->latitude, $latitude);
        self::assertEquals($mapsDto->longitude, $longitude);
    }

    public function mapsDataProvider() {
        return [
          ['133, East Jackson Street, Jackson Ward, Richmond, Richmond City, Virginia, 23219, United States of America', 37.54854349478068,  -77.43726349745914],
          ['Washington, District of Columbia, 20500, United States of America', 38.8948932, -77.0365529],
          ['Barcelona, Barcelonès, Barcelona, Catalunya, España', 41.3828939,  2.1774322],
        ];
    }
}
